version: '3'
services:
  flood:
    build:
      context: "./flood"
    ports:
      - "3000:3000"
    networks:
      - backend
    tty: true
    restart: always
networks:
  backend:
    driver: "bridge"